"""Atomic persistence for files generated by the plugin."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Iterable, Set

logger = logging.getLogger(__name__)


class GeneratedFileManifest:
    """Read and write the generated-file index without partial JSON files."""

    @staticmethod
    def _normalize(path: str) -> str:
        return os.path.normcase(os.path.abspath(os.path.normpath(str(path))))

    @classmethod
    def load(cls, manifest_path: str) -> Set[str]:
        try:
            path = Path(manifest_path)
            if not path.is_file():
                return set()
            with path.open("r", encoding="utf-8") as file:
                data = json.load(file)
            if isinstance(data, list):
                return {cls._normalize(item) for item in data if item}
        except (OSError, ValueError) as err:
            logger.warning(f"读取已生成文件清单失败：{err}")
        return set()

    @classmethod
    def save(cls, manifest_path: str, files: Iterable[str]):
        try:
            path = Path(manifest_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            data = sorted(cls._normalize(item) for item in files if item)
            temp_file = path.with_name(f".{path.name}.tmp")
            with temp_file.open("w", encoding="utf-8") as file:
                json.dump(data, file, ensure_ascii=False, indent=2)
            os.replace(str(temp_file), str(path))
        except OSError as err:
            logger.warning(f"保存已生成文件清单失败：{err}")
